version: "3"
services:
  test:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db
  web:
    image: openjdk:11-jdk
    volumes:
      - ./target/MySurvey-0.0.1-SNAPSHOT.jar:/usr/src/app/app.jar
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/usr/src/app/app.jar"]
