name: Jacoco Code Coverage

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Build and test
        run: mvn clean verify

      - name: Upload Jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco

  generate-badge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Jacoco report
        uses: actions/download-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Generate Jacoco Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: "target/site/jacoco"
          generate-coverage-badge: true
          coverage-badge-filename: jacoco.svg